In [48]:
from tensorflow.keras.preprocessing.text import one_hot

In [49]:
import tensorflow as tf
print(tf.__version__)

2.21.0


In [37]:
import sys
print(sys.executable)

c:\Users\chint\Udemy final\Python\venv\python.exe


In [50]:
## sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
    'Iam a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [39]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'Iam a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [40]:
## define the vocabulary size
voc_size=10000


In [41]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'Iam a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [42]:
##one hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7169, 7844, 8226, 2465],
 [7169, 7844, 8226, 7795],
 [7169, 1010, 8226, 2162],
 [163, 912, 1119, 5919],
 [6196, 1962, 912, 1119, 2812],
 [400, 7169, 9691, 8226, 505],
 [2837, 6764, 8485, 1119]]

In [43]:
##word Embedding Represnetation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [44]:
import numpy as np

In [45]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7169 7844 8226 2465]
 [   0    0    0    0 7169 7844 8226 7795]
 [   0    0    0    0 7169 1010 8226 2162]
 [   0    0    0    0  163  912 1119 5919]
 [   0    0    0 6196 1962  912 1119 2812]
 [   0    0    0  400 7169 9691 8226  505]
 [   0    0    0    0 2837 6764 8485 1119]]


In [46]:
##feature reprenstation
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(voc_size, dim)
])

model.compile(optimizer='adam', loss='mse')

In [54]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step


array([[[-4.99865785e-02, -4.50055599e-02, -4.23522703e-02,
          8.67122412e-03,  1.52272843e-02, -1.37523524e-02,
          4.58766334e-02,  2.11628415e-02, -9.51321051e-03,
         -2.39956975e-02],
        [-4.99865785e-02, -4.50055599e-02, -4.23522703e-02,
          8.67122412e-03,  1.52272843e-02, -1.37523524e-02,
          4.58766334e-02,  2.11628415e-02, -9.51321051e-03,
         -2.39956975e-02],
        [-4.99865785e-02, -4.50055599e-02, -4.23522703e-02,
          8.67122412e-03,  1.52272843e-02, -1.37523524e-02,
          4.58766334e-02,  2.11628415e-02, -9.51321051e-03,
         -2.39956975e-02],
        [-4.99865785e-02, -4.50055599e-02, -4.23522703e-02,
          8.67122412e-03,  1.52272843e-02, -1.37523524e-02,
          4.58766334e-02,  2.11628415e-02, -9.51321051e-03,
         -2.39956975e-02],
        [-2.41040830e-02,  4.97457497e-02,  2.69364975e-02,
          4.56966050e-02, -1.64807066e-02,  6.85906410e-03,
         -4.97710221e-02,  1.47833116e-02,  2.637945